### ISSUE TITLE
EgoGCN/GATConv_pre.py/39行的操作疑问

### ISSUE THREAD

**Issue by lyWen0229** [feiyuchen7/EgoGCN#1]
作者您好，EgoGCN/GATConv_pre.py/39行的操作中，您对x_i进行修改，但是返回的却是x_j。因此这里x_i的融合操作不会生效。不知是否是我理解的有问题。非常期望您解答一下。

**Comment by feiyuchen7** [comment]
你好，是会生效的，因为49行alpha的计算用到了融合后的x_i, 然后alpha也用于了输出

**Comment by LYWen0229** [comment]
非常感谢解答，所以不同模态的特征只会影响这个权重alpha，但是不会影响节点的特征大小，因为如果没有reattn，那么会直接返回x_j而不是修改后的x_i，是这样吗，非常感谢。

**Comment by lyWen0229** [comment]
非常感谢解答
